### ISSUE TITLE
Publishing in PyPI?

### ISSUE THREAD

**Issue by russoz** [ssbostan/maasta#2]
Hi Saied,

First and foremost, thank you for publishing this code. At our company we are looking for better ways to automate infra provisioning, and we bumped into your article about MAASTA and from there into this repo.

I see you are not publishing this package in PyPI. Any specific reason for that? Any chance we are going to see that happening? Thanks!

Cheers

**Comment by ssbostan** [comment]
Hey there,

Happy to hear that.

The new version will be published through PyPI.

Good luck.

**Comment by ssbostan** [comment]
You can install the stable version with `pip install maasta` command.

**Comment by russoz** [comment]
Thanks!!!
